# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               PSYMAZE
tagline:             ''
description:         'A Maze Between Mind and Sound. Written by CMour'
url:                 #
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              CMour
  url:               https://psymaze.com
  email:             cmour@pm.me
# Custom vars
version:             1.1.0

